### ISSUE TITLE
Lab 01 instructions link broken

### ISSUE THREAD

**Issue by Johaning** [DS4PS/cpp-523-spr-2021#1]
The link to Lab 01 instructions is giving a 404 error: 
https://github.com/DS4PS/cpp-523-spr-2021/raw/master/labs/Lab-01-Regression-Review.docx

**Comment by lecy** [comment]
Give it one minute and try again. 

GitHub changed some links from "master" to "main" branch.  So the document will be at: 

https://github.com/DS4PS/cpp-523-spr-2021/raw/main/labs/Lab-01-Regression-Review.docx

**Comment by Johaning** [comment]
Thanks, that works!
