### ISSUE TITLE
Link broken for Specification Bias II lecture in Week 6

### ISSUE THREAD

**Issue by jacobtnyoung** [DS4PS/cpp-523-spr-2021#13]
The link for the Specification Bias II lecture (https://github.com/DS4PS/cpp-523-spr-2020/raw/main/lectures/p-09-specification.pdf) returns a 404 error. This works though:

https://github.com/DS4PS/cpp-523-spr-2021/raw/main/lectures/p-09-specification.pdf

**Comment by lecy** [comment]
Thanks for catching that.
