### ISSUE TITLE
Specification Bias I lecture typos

### ISSUE THREAD

**Issue by jacobtnyoung** [DS4PS/cpp-523-spr-2021#14]
Hi Jesse,

Just noticed a few things on the Specification Bias I lecture.

1. The 3rd plot in the "Logged Models" section should be titled "Linear-Log Model".
2. In the "Nonlinear Relationships" section the sentence reads "providing a little big might"; replace "big" with "bit".
3. In the "Interpretation of Program Effects" the word "example" is misspelled.
4. In the "Logging the DV" section, there is an errant period after the $eB1−1$ formula.
5. In the "Calculating Average Pay for a Given Nonprofit Size" section the word "increase" is misspelled in the first sentence.

**Comment by lecy** [comment]
Got 'em, thanks!
