### ISSUE TITLE
Lab 04: Is this a typo in the Warm-Up?

### ISSUE THREAD

**Issue by mtwelker** [DS4PS/cpp-523-spr-2021#17]
In the instructions for lab 04, it says "Based upon the correlation matrix on page 6, draw a Ballentine Venn Diagram with Subjective Well Being as the dependent variable and RSE, CSE, NP."
Is this referring to the correlation matrix immediately above it in the instructions?  If so, I think the Warm-Up should say "ND" instead of "NP."

**Comment by lecy** [comment]
You are right on both accounts. Thanks for catching those. It is updated.
