### ISSUE TITLE
Is this a typo on page 7 of the "Standard Errors" lecture notes?

### ISSUE THREAD

**Issue by mtwelker** [DS4PS/cpp-523-spr-2021#3]
The second-to-last sentence says "The important thing to note is the unexplained portion shows up in the denominator of the standard error."   Am I missing something, or should it say "numerator" instead of "denominator?"

**Comment by lecy** [comment]
You are correct - it is a typo. It's been updated. 

Congrats, you are the first student in 5 semesters to point this out!

**Comment by mtwelker** [comment]
Haha!  Thanks!
